// Generated by CoffeeScript 2.5.1
(function() {
  var ACCEPTED, NO_CONTENT, app, express, port, users;

  express = require('express');

  port = 3000;

  app = express();

  users = [];

  app.get('/', function(_, res) {
    return res.send('Hello World!');
  });

  app.get('/users', function(_, res) {
    return res.send(users);
  });

  app.post('/user', function(_, res) {
    var u;
    u = {
      id: users.length
    };
    users.push(u);
    return res.send(u);
  });

  app.get('/user/:id', function(req, res) {
    return res.send(users[req.params.id]);
  });

  ACCEPTED = 202;

  NO_CONTENT = 204;

  app.delete('/user/:id', function(req, res) {
    var n, s;
    n = req.params.id;
    s = NO_CONTENT;
    if (users[n] != null) {
      users.splice(n);
      s = ACCEPTED;
    }
    return res.status(s).send();
  });

  app.listen(port, function() {
    return console.log(`Example app listening at http://localhost:${port}`);
  });

}).call(this);
