// Generated by CoffeeScript 2.5.1
(function() {
  var app, express, port, users;

  express = require('express');

  port = 3000;

  app = express();

  users = [];

  app.get('/', function(_, res) {
    return res.send('Hello World!');
  });

  app.get('/users', function(_, res) {
    return res.send(users);
  });

  app.post('/user', function(_, res) {
    var u;
    u = {
      id: users.length
    };
    users.push(u);
    return res.send(u);
  });

  app.get('/user/:id', function(req, res) {
    return res.send(users[req.params.id]);
  });

  app.listen(port, function() {
    return console.log(`Example app listening at http://localhost:${port}`);
  });

}).call(this);
