// Generated by CoffeeScript 2.5.1
(function() {
  var app, express, port;

  express = require('express');

  port = 3000;

  app = express();

  app.get('/', function(_, res) {
    return res.send('Hello World!');
  });

  app.get('/users', function(_, res) {
    return res.send([]);
  });

  app.listen(port, function() {
    return console.log(`Example app listening at http://localhost:${port}`);
  });

}).call(this);
